import type { AiStylePreset } from "./types";

export const AI_STYLE_CATEGORIES = [
  "Cloud styles",
  "Stickers",
  "Line art",
  "Local effects",
] as const;

export const AI_STYLE_PRESETS: AiStylePreset[] = [
  {
    id: "color_cartoon",
    version: "2026.06-direct-fal",
    name: "Color Cartoon",
    category: "Cloud styles",
    previewAsset: "preview://ai-styles/color-cartoon",
    description: "Friendly gift cartoon. Uses direct fal during local testing; proxy/credits can replace the transport later.",
    estimatedCredits: 1,
    estimatedCostUsd: 0.04,
    localCapability: "unavailable",
    cloudCapability: "required",
    requiresCloud: true,
    defaultOptions: { strength: "normal", backgroundMode: "keep", faceMode: "auto" },
    pipeline: [
      { id: "style", type: "cloud-style", label: "Locked cartoon prompt", local: false, modelId: "fal-ai/flux-pro/kontext", promptKey: "cartoon_v1" },
      { id: "quality", type: "quality-check", label: "Print quality check", local: true },
    ],
  },
  {
    id: "watercolor",
    version: "2026.06-direct-fal",
    name: "Watercolor",
    category: "Cloud styles",
    previewAsset: "preview://ai-styles/watercolor",
    description: "Soft watercolor portrait or family illustration via direct fal during testing.",
    estimatedCredits: 1,
    estimatedCostUsd: 0.04,
    localCapability: "unavailable",
    cloudCapability: "required",
    requiresCloud: true,
    defaultOptions: { strength: "normal", backgroundMode: "keep", faceMode: "auto" },
    pipeline: [
      { id: "style", type: "cloud-style", label: "Locked watercolor prompt", local: false, modelId: "fal-ai/flux-pro/kontext", promptKey: "watercolor_v1" },
      { id: "quality", type: "quality-check", label: "Print quality check", local: true },
    ],
  },
  {
    id: "oil_painting",
    version: "2026.06-direct-fal",
    name: "Oil Painting",
    category: "Cloud styles",
    previewAsset: "preview://ai-styles/oil-painting",
    description: "Canvas-ready painterly style via direct fal during testing.",
    estimatedCredits: 1,
    estimatedCostUsd: 0.04,
    localCapability: "unavailable",
    cloudCapability: "required",
    requiresCloud: true,
    defaultOptions: { strength: "normal", backgroundMode: "keep", faceMode: "auto" },
    pipeline: [
      { id: "style", type: "cloud-style", label: "Locked oil painting prompt", local: false, modelId: "fal-ai/flux-pro/kontext", promptKey: "oil_painting_v1" },
      { id: "quality", type: "quality-check", label: "Print quality check", local: true },
    ],
  },
  {
    id: "childrens_book",
    version: "2026.06-direct-fal",
    name: "Children's Book",
    category: "Cloud styles",
    previewAsset: "preview://ai-styles/childrens-book",
    description: "Warm children's-book illustration. Uses Qwen Pro direct fal while testing.",
    estimatedCredits: 2,
    estimatedCostUsd: 0.075,
    localCapability: "unavailable",
    cloudCapability: "required",
    requiresCloud: true,
    defaultOptions: { strength: "normal", backgroundMode: "keep", faceMode: "high" },
    pipeline: [
      { id: "style", type: "cloud-style", label: "Locked storybook prompt", local: false, modelId: "fal-ai/qwen-image-2/pro/edit", promptKey: "childrens_book_v1" },
      { id: "quality", type: "quality-check", label: "Face safety quality check", local: true },
    ],
  },
  {
    id: "romantic_couple",
    version: "2026.06-direct-fal",
    name: "Romantic Couple",
    category: "Cloud styles",
    previewAsset: "preview://ai-styles/romantic-couple",
    description: "Soft romantic couple illustration for canvas, glass and acrylic gift products.",
    estimatedCredits: 1,
    estimatedCostUsd: 0.04,
    localCapability: "unavailable",
    cloudCapability: "required",
    requiresCloud: true,
    defaultOptions: { strength: "normal", backgroundMode: "keep", faceMode: "high" },
    pipeline: [
      { id: "style", type: "cloud-style", label: "Locked romantic couple prompt", local: false, modelId: "fal-ai/flux-pro/kontext", promptKey: "romantic_couple_v1" },
      { id: "quality", type: "quality-check", label: "Couple face safety check", local: true },
    ],
  },
  {
    id: "soft_anime_storybook",
    version: "2026.06-direct-fal",
    name: "Soft Anime Storybook",
    category: "Cloud styles",
    previewAsset: "preview://ai-styles/soft-anime-storybook",
    description: "Warm cinematic anime-inspired storybook look, suitable for gifts and posters.",
    estimatedCredits: 1,
    estimatedCostUsd: 0.04,
    localCapability: "unavailable",
    cloudCapability: "required",
    requiresCloud: true,
    defaultOptions: { strength: "normal", backgroundMode: "keep", faceMode: "auto" },
    pipeline: [
      { id: "style", type: "cloud-style", label: "Locked soft anime prompt", local: false, modelId: "fal-ai/flux-pro/kontext", promptKey: "soft_anime_storybook_v1" },
      { id: "quality", type: "quality-check", label: "Print quality check", local: true },
    ],
  },
  {
    id: "elegant_glass_portrait",
    version: "2026.06-direct-fal",
    name: "Elegant Glass Portrait",
    category: "Cloud styles",
    previewAsset: "preview://ai-styles/elegant-glass-portrait",
    description: "Clean premium portrait treatment for glass blocks and acrylic products.",
    estimatedCredits: 1,
    estimatedCostUsd: 0.04,
    localCapability: "unavailable",
    cloudCapability: "required",
    requiresCloud: true,
    defaultOptions: { strength: "soft", backgroundMode: "clean", faceMode: "high" },
    pipeline: [
      { id: "style", type: "cloud-style", label: "Locked elegant glass prompt", local: false, modelId: "fal-ai/flux-pro/kontext", promptKey: "elegant_glass_portrait_v1" },
      { id: "quality", type: "quality-check", label: "Portrait quality check", local: true },
    ],
  },
  {
    id: "warm_family_storybook",
    version: "2026.06-direct-fal",
    name: "Warm Family Storybook",
    category: "Cloud styles",
    previewAsset: "preview://ai-styles/warm-family-storybook",
    description: "Gentle family illustration, warmer and more mature than the children book preset.",
    estimatedCredits: 2,
    estimatedCostUsd: 0.08,
    localCapability: "unavailable",
    cloudCapability: "required",
    requiresCloud: true,
    defaultOptions: { strength: "normal", backgroundMode: "keep", faceMode: "high" },
    pipeline: [
      { id: "style", type: "cloud-style", label: "Locked family storybook prompt", local: false, modelId: "fal-ai/flux-pro/kontext/max/multi", promptKey: "warm_family_storybook_v1" },
      { id: "quality", type: "quality-check", label: "Multi-face quality check", local: true },
    ],
  },
  {
    id: "pet_gift_cartoon",
    version: "2026.06-direct-fal",
    name: "Pet Gift Cartoon",
    category: "Cloud styles",
    previewAsset: "preview://ai-styles/pet-gift-cartoon",
    description: "Friendly pet cartoon for mugs, stickers, shirts and playful gifts.",
    estimatedCredits: 1,
    estimatedCostUsd: 0.04,
    localCapability: "unavailable",
    cloudCapability: "required",
    requiresCloud: true,
    defaultOptions: { strength: "normal", backgroundMode: "transparent", faceMode: "auto" },
    pipeline: [
      { id: "style", type: "cloud-style", label: "Locked pet cartoon prompt", local: false, modelId: "fal-ai/flux-pro/kontext", promptKey: "pet_gift_cartoon_v1" },
      { id: "rmbg", type: "local-rmbg", label: "Optional transparent cutout", local: true, optional: true },
      { id: "quality", type: "quality-check", label: "Print quality check", local: true },
    ],
  },
  {
    id: "memorial_pencil_portrait",
    version: "2026.06-direct-fal",
    name: "Memorial Pencil Portrait",
    category: "Cloud styles",
    previewAsset: "preview://ai-styles/memorial-pencil-portrait",
    description: "Respectful black-and-white pencil portrait for memory products.",
    estimatedCredits: 1,
    estimatedCostUsd: 0.04,
    localCapability: "partial",
    cloudCapability: "required",
    requiresCloud: true,
    defaultOptions: { strength: "soft", backgroundMode: "clean", faceMode: "high" },
    pipeline: [
      { id: "style", type: "cloud-style", label: "Locked memorial pencil prompt", local: false, modelId: "fal-ai/flux-pro/kontext", promptKey: "memorial_pencil_portrait_v1" },
      { id: "quality", type: "quality-check", label: "Portrait quality check", local: true },
    ],
  },
  {
    id: "cute_sticker",
    version: "2026.06-local",
    name: "Cute Sticker",
    category: "Stickers",
    previewAsset: "preview://ai-styles/cute-sticker",
    description: "Local subject cutout with a clean white sticker border.",
    estimatedCredits: 0,
    estimatedCostUsd: 0,
    localCapability: "ready",
    cloudCapability: "optional",
    requiresCloud: false,
    defaultOptions: { strength: "normal", backgroundMode: "transparent", faceMode: "auto" },
    pipeline: [
      { id: "rmbg", type: "local-rmbg", label: "Local subject/background mask", local: true },
      { id: "border", type: "local-effect", label: "Sticker border", local: true, effect: "sticker_border" },
      { id: "export", type: "local-export", label: "Transparent PNG", local: true },
      { id: "quality", type: "quality-check", label: "Alpha quality check", local: true },
    ],
  },
  {
    id: "ai_lineart",
    version: "2026.06-direct-fal",
    name: "AI Line Art",
    category: "Line art",
    previewAsset: "preview://ai-styles/ai-lineart",
    description: "Model-based line extraction for faces and detailed portraits when local edges are not enough.",
    estimatedCredits: 1,
    estimatedCostUsd: 0.01,
    localCapability: "unavailable",
    cloudCapability: "required",
    requiresCloud: true,
    defaultOptions: { strength: "normal", backgroundMode: "transparent", faceMode: "auto" },
    pipeline: [
      { id: "lineart_model", type: "cloud-lineart", label: "fal lineart preprocessor", local: false, modelId: "fal-ai/image-preprocessors/lineart" },
      { id: "export", type: "local-export", label: "Transparent PNG", local: true },
      { id: "quality", type: "quality-check", label: "Line density check", local: true },
    ],
  },
  {
    id: "line_engraving",
    version: "2026.06-local",
    name: "Line Art / Engraving",
    category: "Line art",
    previewAsset: "preview://ai-styles/line-engraving",
    description: "Local black line output for laser, engraving and coloring workflows.",
    estimatedCredits: 0,
    estimatedCostUsd: 0,
    localCapability: "ready",
    cloudCapability: "none",
    requiresCloud: false,
    defaultOptions: { strength: "normal", backgroundMode: "transparent", faceMode: "auto" },
    pipeline: [
      { id: "line", type: "local-effect", label: "Grayscale edge detect", local: true, effect: "line_art" },
      { id: "export", type: "local-export", label: "Transparent PNG", local: true },
      { id: "quality", type: "quality-check", label: "Line density check", local: true },
    ],
  },
  {
    id: "pencil_sketch",
    version: "2026.06-local",
    name: "Pencil Sketch",
    category: "Local effects",
    previewAsset: "preview://ai-styles/pencil-sketch",
    description: "Fast local pencil sketch approximation.",
    estimatedCredits: 0,
    estimatedCostUsd: 0,
    localCapability: "ready",
    cloudCapability: "optional",
    requiresCloud: false,
    defaultOptions: { strength: "normal", backgroundMode: "keep", faceMode: "auto" },
    pipeline: [
      { id: "sketch", type: "local-effect", label: "Pencil sketch", local: true, effect: "sketch" },
      { id: "quality", type: "quality-check", label: "Basic quality check", local: true },
    ],
  },
  {
    id: "posterize_pop",
    version: "2026.06-local",
    name: "Posterize Pop",
    category: "Local effects",
    previewAsset: "preview://ai-styles/posterize-pop",
    description: "Local poster color reduction for fast gift previews.",
    estimatedCredits: 0,
    estimatedCostUsd: 0,
    localCapability: "ready",
    cloudCapability: "optional",
    requiresCloud: false,
    defaultOptions: { strength: "normal", backgroundMode: "keep", faceMode: "auto" },
    pipeline: [
      { id: "posterize", type: "local-effect", label: "Poster color reduction", local: true, effect: "posterize" },
      { id: "quality", type: "quality-check", label: "Basic quality check", local: true },
    ],
  },
];

export function getAiStylePreset(presetId: string): AiStylePreset | undefined {
  return AI_STYLE_PRESETS.find((preset) => preset.id === presetId);
}

export function aiStyleCategories(): string[] {
  return [...new Set(AI_STYLE_PRESETS.map((preset) => preset.category))];
}
